module.exports = {
    staticFilter: function(url){
        return {
            '//static.mgcheng.com/static/js/merge/account_message.merge.js': '//static.mgcheng.com/static/js/merge/account_message.merge.js?0a53b7',
            '//static.mgcheng.com/static/js/merge/index.merge.js': '//static.mgcheng.com/static/js/merge/index.merge.js?a227de',
            '//static.mgcheng.com/static/js/merge/login.merge.js': '//static.mgcheng.com/static/js/merge/login.merge.js?fb8b09',
            '//static.mgcheng.com/static/js/merge/main_home.merge.js': '//static.mgcheng.com/static/js/merge/main_home.merge.js?4b44ae',
            '//static.mgcheng.com/static/js/merge/personal_account.merge.js': '//static.mgcheng.com/static/js/merge/personal_account.merge.js?6d9bf8',
            '//static.mgcheng.com/static/js/merge/personal_order.merge.js': '//static.mgcheng.com/static/js/merge/personal_order.merge.js?d7f9a9',
            '//static.mgcheng.com/static/js/merge/personal_orderdetail.merge.js': '//static.mgcheng.com/static/js/merge/personal_orderdetail.merge.js?22e442',
            '//static.mgcheng.com/static/js/merge/personal_package.merge.js': '//static.mgcheng.com/static/js/merge/personal_package.merge.js?9e0938',
            '//static.mgcheng.com/static/js/merge/personal_packagesetting.merge.js': '//static.mgcheng.com/static/js/merge/personal_packagesetting.merge.js?e087d8',
            '//static.mgcheng.com/static/js/merge/personal_photo.merge.js': '//static.mgcheng.com/static/js/merge/personal_photo.merge.js?60aa7d',
            '//static.mgcheng.com/static/js/merge/personal_setting.merge.js': '//static.mgcheng.com/static/js/merge/personal_setting.merge.js?1daba7',
            '//static.mgcheng.com/static/js/merge/profile_about.merge.js': '//static.mgcheng.com/static/js/merge/profile_about.merge.js?8a3d92',
            '//static.mgcheng.com/static/js/merge/profile_index.merge.js': '//static.mgcheng.com/static/js/merge/profile_index.merge.js?ed8ded',
            '//static.mgcheng.com/static/js/merge/profile_package.merge.js': '//static.mgcheng.com/static/js/merge/profile_package.merge.js?9930a4',
            '//static.mgcheng.com/static/js/merge/profile_trade.merge.js': '//static.mgcheng.com/static/js/merge/profile_trade.merge.js?d344f2',
            '//static.mgcheng.com/static/js/merge/register.merge.js': '//static.mgcheng.com/static/js/merge/register.merge.js?41dfe0',
            '//static.mgcheng.com/static/js/merge/search_photo.merge.js': '//static.mgcheng.com/static/js/merge/search_photo.merge.js?b1c07c',
            '//static.mgcheng.com/static/mobile/js/merge/login.merge.js': '//static.mgcheng.com/static/mobile/js/merge/login.merge.js?c42f84',
            '//static.mgcheng.com/static/mobile/js/merge/mobile.merge.js': '//static.mgcheng.com/static/mobile/js/merge/mobile.merge.js?27adf3',
            '//static.mgcheng.com/static/css/merge/account_message.merge.css': '//static.mgcheng.com/static/css/merge/account_message.merge.css?5b3afd',
            '//static.mgcheng.com/static/css/merge/error.merge.css': '//static.mgcheng.com/static/css/merge/error.merge.css?dedc55',
            '//static.mgcheng.com/static/css/merge/index.merge.css': '//static.mgcheng.com/static/css/merge/index.merge.css?64d026',
            '//static.mgcheng.com/static/css/merge/login.merge.css': '//static.mgcheng.com/static/css/merge/login.merge.css?5e8b3b',
            '//static.mgcheng.com/static/css/merge/main_home.merge.css': '//static.mgcheng.com/static/css/merge/main_home.merge.css?8b6cd1',
            '//static.mgcheng.com/static/css/merge/personal_account.merge.css': '//static.mgcheng.com/static/css/merge/personal_account.merge.css?45062c',
            '//static.mgcheng.com/static/css/merge/personal_order.merge.css': '//static.mgcheng.com/static/css/merge/personal_order.merge.css?760d91',
            '//static.mgcheng.com/static/css/merge/personal_orderdetail.merge.css': '//static.mgcheng.com/static/css/merge/personal_orderdetail.merge.css?d77cc6',
            '//static.mgcheng.com/static/css/merge/personal_package.merge.css': '//static.mgcheng.com/static/css/merge/personal_package.merge.css?274548',
            '//static.mgcheng.com/static/css/merge/personal_packagesetting.merge.css': '//static.mgcheng.com/static/css/merge/personal_packagesetting.merge.css?ac3d1f',
            '//static.mgcheng.com/static/css/merge/personal_photo.merge.css': '//static.mgcheng.com/static/css/merge/personal_photo.merge.css?fa0eba',
            '//static.mgcheng.com/static/css/merge/personal_setting.merge.css': '//static.mgcheng.com/static/css/merge/personal_setting.merge.css?8bef38',
            '//static.mgcheng.com/static/css/merge/profile_about.merge.css': '//static.mgcheng.com/static/css/merge/profile_about.merge.css?61403e',
            '//static.mgcheng.com/static/css/merge/profile_index.merge.css': '//static.mgcheng.com/static/css/merge/profile_index.merge.css?1bc261',
            '//static.mgcheng.com/static/css/merge/profile_package.merge.css': '//static.mgcheng.com/static/css/merge/profile_package.merge.css?5a410a',
            '//static.mgcheng.com/static/css/merge/profile_trade.merge.css': '//static.mgcheng.com/static/css/merge/profile_trade.merge.css?0ca8a1',
            '//static.mgcheng.com/static/css/merge/register.merge.css': '//static.mgcheng.com/static/css/merge/register.merge.css?f6309e',
            '//static.mgcheng.com/static/css/merge/search_photo.merge.css': '//static.mgcheng.com/static/css/merge/search_photo.merge.css?6fcd8d',
            '//static.mgcheng.com/static/mobile/css/merge/login.merge.css': '//static.mgcheng.com/static/mobile/css/merge/login.merge.css?021bef',
            '//static.mgcheng.com/static/mobile/css/merge/mobile.merge.css': '//static.mgcheng.com/static/mobile/css/merge/mobile.merge.css?048741'
        }[url]
    }
}