module.exports = {
    staticFilter: function(url){
        return {
            '//static.mgcheng.com/static/js/merge/account_message.merge.js': '//static.mgcheng.com/static/js/merge/account_message.merge.js?8a25ae',
            '//static.mgcheng.com/static/js/merge/index.merge.js': '//static.mgcheng.com/static/js/merge/index.merge.js?3ac878',
            '//static.mgcheng.com/static/js/merge/login.merge.js': '//static.mgcheng.com/static/js/merge/login.merge.js?744632',
            '//static.mgcheng.com/static/js/merge/main_home.merge.js': '//static.mgcheng.com/static/js/merge/main_home.merge.js?ad64d0',
            '//static.mgcheng.com/static/js/merge/personal_order.merge.js': '//static.mgcheng.com/static/js/merge/personal_order.merge.js?5a341e',
            '//static.mgcheng.com/static/js/merge/personal_orderdetail.merge.js': '//static.mgcheng.com/static/js/merge/personal_orderdetail.merge.js?dcde05',
            '//static.mgcheng.com/static/js/merge/personal_package.merge.js': '//static.mgcheng.com/static/js/merge/personal_package.merge.js?bca88d',
            '//static.mgcheng.com/static/js/merge/personal_packagesetting.merge.js': '//static.mgcheng.com/static/js/merge/personal_packagesetting.merge.js?1e2a8c',
            '//static.mgcheng.com/static/js/merge/personal_photo.merge.js': '//static.mgcheng.com/static/js/merge/personal_photo.merge.js?57fcba',
            '//static.mgcheng.com/static/js/merge/personal_setting.merge.js': '//static.mgcheng.com/static/js/merge/personal_setting.merge.js?a5b1cb',
            '//static.mgcheng.com/static/js/merge/profile_about.merge.js': '//static.mgcheng.com/static/js/merge/profile_about.merge.js?71d7c9',
            '//static.mgcheng.com/static/js/merge/profile_index.merge.js': '//static.mgcheng.com/static/js/merge/profile_index.merge.js?872a9b',
            '//static.mgcheng.com/static/js/merge/profile_package.merge.js': '//static.mgcheng.com/static/js/merge/profile_package.merge.js?01bc59',
            '//static.mgcheng.com/static/js/merge/profile_trade.merge.js': '//static.mgcheng.com/static/js/merge/profile_trade.merge.js?5138d2',
            '//static.mgcheng.com/static/js/merge/register.merge.js': '//static.mgcheng.com/static/js/merge/register.merge.js?638995',
            '//static.mgcheng.com/static/js/merge/search_photo.merge.js': '//static.mgcheng.com/static/js/merge/search_photo.merge.js?a11fad',
            '//static.mgcheng.com/static/mobile/js/merge/login.merge.js': '//static.mgcheng.com/static/mobile/js/merge/login.merge.js?c3932c',
            '//static.mgcheng.com/static/mobile/js/merge/mobile.merge.js': '//static.mgcheng.com/static/mobile/js/merge/mobile.merge.js?240dd3',
            '//static.mgcheng.com/static/css/merge/account_message.merge.css': '//static.mgcheng.com/static/css/merge/account_message.merge.css?45799c',
            '//static.mgcheng.com/static/css/merge/error.merge.css': '//static.mgcheng.com/static/css/merge/error.merge.css?68d30a',
            '//static.mgcheng.com/static/css/merge/index.merge.css': '//static.mgcheng.com/static/css/merge/index.merge.css?696425',
            '//static.mgcheng.com/static/css/merge/login.merge.css': '//static.mgcheng.com/static/css/merge/login.merge.css?fd1db1',
            '//static.mgcheng.com/static/css/merge/main_home.merge.css': '//static.mgcheng.com/static/css/merge/main_home.merge.css?ff71d3',
            '//static.mgcheng.com/static/css/merge/personal_order.merge.css': '//static.mgcheng.com/static/css/merge/personal_order.merge.css?3311df',
            '//static.mgcheng.com/static/css/merge/personal_orderdetail.merge.css': '//static.mgcheng.com/static/css/merge/personal_orderdetail.merge.css?1be19f',
            '//static.mgcheng.com/static/css/merge/personal_package.merge.css': '//static.mgcheng.com/static/css/merge/personal_package.merge.css?f6c275',
            '//static.mgcheng.com/static/css/merge/personal_packagesetting.merge.css': '//static.mgcheng.com/static/css/merge/personal_packagesetting.merge.css?54b093',
            '//static.mgcheng.com/static/css/merge/personal_photo.merge.css': '//static.mgcheng.com/static/css/merge/personal_photo.merge.css?cf70c2',
            '//static.mgcheng.com/static/css/merge/personal_setting.merge.css': '//static.mgcheng.com/static/css/merge/personal_setting.merge.css?5c639e',
            '//static.mgcheng.com/static/css/merge/profile_about.merge.css': '//static.mgcheng.com/static/css/merge/profile_about.merge.css?be0f82',
            '//static.mgcheng.com/static/css/merge/profile_index.merge.css': '//static.mgcheng.com/static/css/merge/profile_index.merge.css?630069',
            '//static.mgcheng.com/static/css/merge/profile_package.merge.css': '//static.mgcheng.com/static/css/merge/profile_package.merge.css?3282cb',
            '//static.mgcheng.com/static/css/merge/profile_trade.merge.css': '//static.mgcheng.com/static/css/merge/profile_trade.merge.css?03ab7c',
            '//static.mgcheng.com/static/css/merge/register.merge.css': '//static.mgcheng.com/static/css/merge/register.merge.css?2714a4',
            '//static.mgcheng.com/static/css/merge/search_photo.merge.css': '//static.mgcheng.com/static/css/merge/search_photo.merge.css?2ca4ad',
            '//static.mgcheng.com/static/mobile/css/merge/login.merge.css': '//static.mgcheng.com/static/mobile/css/merge/login.merge.css?06598d',
            '//static.mgcheng.com/static/mobile/css/merge/mobile.merge.css': '//static.mgcheng.com/static/mobile/css/merge/mobile.merge.css?4ed088'
        }[url]
    }
}